### ISSUE TITLE
Android terminated state call not working

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [ConnectyCube/connectycube-flutter-call-kit#114]
Hey!

The callkit call notification display was working perfectly a few days back for both when the app is in the background or terminated using the methods provided in the documentation for when the app is terminated.
All of a sudden since yestarday I've not been able to receive callkit calls (no call display appears) when the app is terminated (i have made no changes to the working code), however the function "onCallAcceptedWhenTerminated" works when the app receives a call in the background and a user accepts (all this while the app is not in the foreground)?

**Comment by TatankaConCube** [comment]
We haven't changed anything in the plugin for a long time too))) I met the case when the plugin didn't show the notification after running the app in debug (from the Android Studio) and then killing it. Then after starting the app by the app icon and killing it, the plugin starts working correctly. It happens because the IDE starts the app with some arguments and after killing the app the system can't run the app with the same arguments.

**Comment by AbdurrehmanSubhani** [comment]
I tried the method you've mentioned above but it still did not work,
i just released a test version of my application to testers who reported receiving the call notification in the terminated state on Android till the previous week until recently for the past couple of days they reported the feature to have not been working. Would this have to do with the recent updates on the connectycube sdk?

**Comment by TatankaConCube** [comment]
> Would this have to do with the recent updates on the connectycube sdk?

no, the SDK can't have an affect on it, especially since the changes were related to the calls only, not to the push notifications

**Comment by AbdurrehmanSubhani** [comment]
- Issue: Firebase messaging notification was not being delivered to the device, once the notification delivery worked, callkit works as expected, sorry for this issue
