### ISSUE TITLE
Terminated state callbacks doesn't fire on Android 9

### ISSUE THREAD

**Issue by salamaEnigma** [ConnectyCube/connectycube-flutter-call-kit#48]
Hi, Thanks for the great plugin.
I'm having an issue with the terminated state callbacks
_they works fine when tested on Android 11._

**but** with Android 8/9 they are not fired at all.
weirdly though the callbacks are fired only when **the app is terminated and the device is locked** .
if the app is terminated and the device is _unlocked_ it doesn't work!

to be more specific I found that this line in the `EventReceiver.kt` file 
never runs:
`ConnectycubeFlutterBgPerformingService.enqueueMessageProcessing(context,broadcastIntent)`

Any idea what I'm doing wrong, or what might be the cause of this behavior ?

O.S : Android 9
Device : Huawei Nova 3i

**Comment by kortobaaEnigma** [comment]
I found out that the reason why this line never runs
`ConnectycubeFlutterBgPerformingService.enqueueMessageProcessing(context,broadcastIntent)`

is because of the check before 

`if (!isApplicationForeground(context))`


I think the problem lies here in the `AppUtils.kt` file
```
   for (appProcess in appProcesses) {
        if (appProcess.importance == ActivityManager.RunningAppProcessInfo.IMPORTANCE_FOREGROUND
            && appProcess.processName == packageName
        ) {
            return true
        }
    }
```

it returns `true` in Android 9 when it should returns `false`
